version: '3'
services:
  cart_db:
    image: mysql:5.7.24
    restart: always
    container_name: cart_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cart_db
    ports:
      - '3309:3306'
    networks:
      myapp_net:
        ipv4_address: 172.16.238.11
  cart-server:
    container_name: cart-server
    build:
      context: ./cart-server
      dockerfile: Dockerfile
    volumes:
      - ./cart-server:/var/www/cart-server
    ports:
      - 9005:80
    networks:
      myapp_net:
        ipv4_address: 172.16.238.12
networks:
  myapp_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
